### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by johanneskoester** [snakemake-workflows/single-cell-rna-seq#1]
This workflow shall be extended as new types of analyses emerge. Please feel free to contribute or suggest further items to be added.

* [ ] Add kallisto-based step for calculating per-cell abundances, also considering UMIs.
* [ ] infer trajectories with STREAM
* [ ] cluster with SC3
* [ ] infer RNA velocity with velocyto
